name: self test

on:
  workflow_dispatch:

jobs:
  python-tests:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      # you probably would want to use a higher version
      - uses: actions/checkout@v2

      # uses set-output which is deprecated
      - id: changes
        uses: jitterbit/get-changed-files@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Python Tests
        run: |
          cd python
          python3 translator.self.test.py